version: '3'

services:
  website:
    restart: always
    build:
      context: .
      dockerfile: ./telesoccorso/Dockerfile
    container_name: telesoccorso
    image: telesoccorso
    ports:
      - 80:80
    depends_on:
      - database
    networks:
      network-tsc:
        ipv4_address: 10.5.0.2
   
  database:
    restart: always
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: database
    image: database
    ports:
      - 3306:3306
    networks:
      network-tsc:
        ipv4_address: 10.5.0.3

networks:
  network-tsc:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16